app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('article/<int:article_id>/', views.article, name='article'),
    path('bookshelves/', views.bookshelves, name='bookshelves'),
    path('bookshelf/<int:bookshelf_id>/', views.bookshelf, name='bookshelf'),
    path('rate/<int:book_id>/<int:rating>/', views.rate),
    path('feedback/', views.feedback, name='feedback'),
    path('new_bookshelf/', views.new_bookshelf, name='new_bookshelf'),
    path('book/<int:book_id>/', views.book_page, name='book'),
    path('delete_bookshelf/<int:bookshelf_id>/', views.delete_bookshelf, name='delete_bookshelf'),
    path('delete_book_from_bookshelf/<int:book_id>/<int:bookshelf_id>/', views.delete_book_from_bookshelf,
         name='delete_book_from_bookshelf'),
    path('search_books/', views.search_books, name='search_books')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg


class Bookshelf(models.Model):
    """Topics by which the user sorts books in his library."""
    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Книжкова полиця'
        verbose_name_plural = 'Книжкові полиці'

    def __str__(self):
        return self.title


class Book(models.Model):
    """Модель книги"""
    bookshelf = models.ManyToManyField(Bookshelf, blank=True)
    title = models.CharField('Назва', max_length=100)
    author = models.CharField('Автор', max_length=100, null=True)
    description = models.TextField('Опис')
    genre = models.CharField('Жанр', max_length=50)
    url_book = models.CharField('Посилання на книгу', max_length=200, blank=True, null=True)
    url_image = models.CharField('Посилання на зображення', max_length=250, null=True)

    def average_rating(self) -> float:
        return Rating.objects.filter(book=self).aggregate(Avg("rating"))["rating__avg"] or 0

    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def __str__(self):
        return f"{self.title}, {self.average_rating()}, {self.author}"


class Rating(models.Model):
    """Модель для додавання оцінок до книги"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.book.title}: {self.rating}"


class Review(models.Model):
    """Модель для створення рецензій до книг"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey('Book', on_delete=models.CASCADE, related_name='reviews')
    text_review = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text_review


class ArticleCategory(models.Model):
    """Модель для створення категорій для сортування статей"""
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Feedback(models.Model):
    """Модель для відгуків та пропозицій"""
    theme = models.CharField('Тема', max_length=250)
    text = models.TextField('Відгук')

    def __str__(self):
        return self.theme


class Article(models.Model):
    """Модель для створення статей"""
    title = models.CharField('Заголовок', max_length=250)
    categories = models.ManyToManyField(ArticleCategory, related_name='articles')
    text = models.TextField("Текст статті")
    image = models.ImageField(upload_to='article_images/', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    books = models.ManyToManyField(Book, related_name='articles')
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

main/forms.py
from django import forms

from .models import Bookshelf, Book, Review, Feedback


class BookshelfForm(forms.ModelForm):
    """Форма для створення полиці"""
    class Meta:
        model = Bookshelf
        fields = ['title']


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['theme', 'text']


class BookForm(forms.ModelForm):
    """Форма для додавання книги до БД"""
    class Meta:
        model = Book
        fields = ['title', 'author']


class SelectBookshelfForm(forms.ModelForm):
    """Додає книгу на конкретну полицю"""
    bookshelf = forms.ModelMultipleChoiceField(
        queryset=Bookshelf.objects.none(),
        widget=forms.SelectMultiple(attrs={'class': 'form-select-lg col-12'}),
        label='',
        required=False
    )

    class Meta:
        model = Book
        fields = ['bookshelf']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(SelectBookshelfForm, self).__init__(*args, **kwargs)
        # Беремо тільки ті елементи "Bookshelf", власниками яких є поточний користувач
        self.fields['bookshelf'].queryset = Bookshelf.objects.filter(user=user)
        self.fields['bookshelf'].label_from_instance = lambda obj: obj.title


class ReviewForm(forms.ModelForm):
    """Форма для додавання рецензій"""
    class Meta:
        model = Review
        fields = ['text_review']
        labels = {
            'text_review': ''
        }
        widgets = {
            'text_review': forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'cols': 40,
                                                 'placeholder': 'Ви можете написати тут свою рецензію на цю книгу'})
        }

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Book, Bookshelf, Rating, Article
from .forms import BookshelfForm, BookForm, SelectBookshelfForm, ReviewForm, FeedbackForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponse, HttpRequest


def index(request):
    """Головна сторінка"""
    articles = Article.objects.all()
    return render(request, 'main/index.html', {'articles': articles})


def article(request, article_id):
    """Сторінка кожної окремої статті"""
    article = get_object_or_404(Article, pk=article_id)
    return render(request, 'main/article.html', {'article': article})


def about(request):
    """Сторінка про нас"""
    return render(request, 'main/about.html')


def rate(request: HttpRequest, book_id: int, rating: int) -> HttpResponse:
    book = Book.objects.get(id=book_id)
    Rating.objects.filter(book=book, user=request.user).delete()
    book.rating_set.create(user=request.user, rating=rating)
    return index(request)


def book_page(request, book_id):
    """Функція, яка обробляє всі події на сторінці конкретної книги."""
    book = get_object_or_404(Book, pk=book_id)

    rating = Rating.objects.filter(book=book, user=request.user).first()
    book.user_rating = rating.rating if rating else 0

    if request.method == 'POST':
        if 'bookshelf' in request.POST:
            bookshelf_form = SelectBookshelfForm(request.POST, instance=book, user=request.user)
            if bookshelf_form.is_valid():
                bookshelf_id = bookshelf_form.cleaned_data['bookshelf'].values_list('id', flat=True).first()
                book = bookshelf_form.save(commit=False)
                book.save()
                bookshelf_form.save_m2m()
                return redirect('main:bookshelf', bookshelf_id=bookshelf_id)
            else:
                review_form = ReviewForm()
        elif 'text_review' in request.POST:
            bookshelf_form = SelectBookshelfForm(instance=book, user=request.user)
            review_form = ReviewForm(request.POST)
            if review_form.is_valid():
                review = review_form.save(commit=False)
                review.book = book
                review.user = request.user
                review.save()
                return redirect('main:book', book_id=book.id)
        else:
            bookshelf_form = SelectBookshelfForm(instance=book, user=request.user)
            review_form = ReviewForm()
    else:
        bookshelf_form = SelectBookshelfForm(instance=book, user=request.user)
        review_form = ReviewForm()

    context = {
        'bookshelf_form': bookshelf_form,
        'book': book,
        'review_form': review_form
    }

    return render(request, 'main/book.html', context)


@login_required
def bookshelf(request, bookshelf_id):
    """Сторінка конкретної полиці"""
    bookshelf = Bookshelf.objects.get(id=bookshelf_id)
    books = bookshelf.book_set.order_by('-id')
    return render(request, 'main/bookshelf.html', {'bookshelf': bookshelf, 'books': books})


@login_required
def delete_bookshelf(request, bookshelf_id):
    """Видалити полицю"""
    bookshelf = Bookshelf.objects.get(pk=bookshelf_id)
    bookshelf.delete()
    return redirect('main:bookshelves')


@login_required
def delete_book_from_bookshelf(request, book_id, bookshelf_id):
    """Прибрати книгу з полиці"""
    book = Book.objects.get(pk=book_id)
    bookshelf = Bookshelf.objects.get(pk=bookshelf_id)
    book.bookshelf.remove(bookshelf)
    return redirect('main:bookshelf', bookshelf_id)


@login_required
def bookshelves(request):
    """Вивід всіх полиць"""
    # Показуємо лише полиці власника і сортуємо за датою
    bookshelves = Bookshelf.objects.filter(user=request.user).order_by('date_added')
    return render(request, 'main/bookshelves.html', {'bookshelves': bookshelves})


@login_required
def new_bookshelf(request):
    if request.method != 'POST':
        form = BookshelfForm()
    else:
        form = BookshelfForm(data=request.POST)
        if form.is_valid():
            new_bookshelf = form.save(commit=False)
            new_bookshelf.user = request.user
            new_bookshelf.save()
            return redirect('main:bookshelves')
    return render(request, 'main/new_bookshelf.html', {'form': form})


def feedback(request):
    """Сторінка з формою для відгуків"""
    if request.method != 'POST':
        form = FeedbackForm()
    else:
        form = FeedbackForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:about')
    return render(request, 'main/feedback.html', {'form': form})


def add_book(request, bookshelf_id):
    """Переробити для додавання рецензій"""
    bookshelf = Bookshelf.objects.get(id=bookshelf_id)
    if request.method != 'POST':
        form = BookForm()
    else:
        form = BookForm(data=request.POST)
        if form.is_valid():
            new_book = form.save(commit=False)
            new_book.bookshelf = bookshelf
            new_book.save()
            return redirect('main:bookshelf', bookshelf_id=bookshelf_id)
    return render(request, 'main/add_book.html', {"bookshelf": bookshelf, 'form': form})


def search_books(request: HttpRequest) -> HttpResponse:
    if request.method != 'POST':
        return render(request, 'main/search_books.html', {})
    else:
        searched = request.POST['searched']
        books = Book.objects.filter(Q(author__iregex=searched) | Q(title__iregex=searched))
        for book in books:
            rating = Rating.objects.filter(book=book, user=request.user).first()
            book.user_rating = rating.rating if rating else 0
        return render(request, 'main/search_books.html', {'searched': searched, 'books': books})

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}Про проект LDb{% endblock %}

{% block content %}

<table>
    <td width="2%"></td>
    <td width="96%">
  <h2>
    Що таке Literature Database?
  </h2>
  <h5 style="font-weight: lighter;">
      <p>
          Literature Database - це проєкт,
          котрий задумувався як соціальна мережа для книголюбів.
          Хоча, початкова концепція - це спроба зробити зручні списки та категорії
          в яких можна зберігати та сортувати книги.
          Ви зараз користуєтесь першою публічною версією цього вебзастосунку.
      <p/>
      <p>
          Мене звати Влад. Я розробник цього проєкту, і створюю його власними силами.
          Паралельно вивчаючи програмування застосовую свої знання саме тут.
          Моя мета - це зробити якісний продукт, яким буде перш за все зручно користуватись.
          Тому я не обійдусь без допомоги кожного з вас.
          Я маю на увазі поради та ідеї для покращення. Буду радий будь-якому фітбеку.
          Його ви можете залишити в формі за посиланням.
      </p>
  </h5>

    <h2>
        Що вже реалізовано?
    </h2>
    <h5 style="font-weight: lighter;">
    <p>
        На данний момент реалізовані такі можливості:
        <ul>
            <li>
                Створення "Книжкових полиць". Це абстракція, маються на увазі категорії для сортування,
                щось на кшталт тек, куди ви можете додати, перенести або звідки видалити книги.
            </li>
            <li>
                Система реєстрації / аутентифікації
            </li>
            <li>
                Сайт має базу даних 20 000 книг. Я вже працюю над оптимізацією та розширенням цієї бази
                (Видалення дублікатів деяких книг, додавання нових, та створення системи фільтрів). Буду вдячний за
                повідомлення через форму звернення, якщо ви не знайшли книгу яку шукали, чи пошук видав декілька схожих
                результатів.
            </li>
            <li>
                Форма пошук книг в базі даних.
            </li>
            <li>
                Додавання коментарів (рецензій) до книг.
            </li>
            <li>
                Рейтинг книг. Дуже прошу активно оцінювати книги, які ви вже прочитали, щоб якомога скоріше
                з'явилась можливість фільтрувати книги за рейтингом.
            </li>
            <li>
                Статті з підбірками книг від поважних видавництв, з яких ви можете додавати книги на свої полиці.
            </li>
        </ul>
    </h5 >
        </p>

    <h2>
        Що знаходиться в процесі реалізації?
    </h2>
    <h5 style="font-weight: lighter;">
        <ul>
            <li>
                Відповідати на рецензії та оцінювати їх.
            </li>
            <li>
                Останні та популярні рецензії на головній сторінці.
            </li>
            <li>
                Можливість робити свої полиці публічними.
            </li>
            <li>
                Сторінка профілю користувача.
            </li>
            <li>
                Пошук серед користувачів.
            </li>
            <li>
                Можливість додаватись в друзі та переглядати полиці своїх друзів.
            </li>
        </ul>
        </h5>

</td>
    <td width="2%"></td>
</table>

{% endblock %}

main/templates/main/add_book.html
{% extends 'main/base.html' %}

{% block title %}Додати книгу{% endblock %}

{% block content %}
  <p>Додати книгу на полицю: </p>

  <form action="{% url 'main:add_book' bookshelf.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Підтвердити</button>
  </form>

{% endblock %}

main/templates/main/article.html
{% extends 'main/base.html' %}

{% block title %}Головна сторінка{% endblock %}

{% block content %}

<center>
    <h1>{{ article.title }}</h1>
</center>
<br/>
<br/>
    <table>
        <tr>
            <td width="15%"></td>
            <td width="70%">
                <center>
                    {% if article.image %}
                        <img src="{{ MEDIA_URL }}{{ article.image.url }}" width="1080" height="500">
                    {% endif %}
                    <br/>
                    <hr>
                        <h3 style="font-weight: lighter;">
                            {{ article.text }}
                        </h3>
                        <br/>
                        <hr>

                    {% for book in article.books.all %}

                    <h3>{{ book.title }}</h3>
                    <br>
                    <h5>{{ book.author }}</h5>
                    <br/>
                    <a href="{% url 'main:book' book.id %}">
                        <img src="{{ book.url_image }}" width="350">
                    </a>
                    <br/>
                    <h4 style="font-weight: lighter;">
                        {{ book.description }}
                    </h4>
                    <hr>
                    <br/>
                    {% endfor %}
                </center>
            </td>
            <td width="15%"></td>
        </tr>
    </table>

{% endblock %}

main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="uk" >

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.rtl.min.css"
          integrity="sha384-WJUUqfoMmnfkBLne5uxXj+na/c7sesSJ32gI7GfCk4zO4GthUKhSEGyvQ839BC51" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <meta charset="UTF-8">
  </head>

  <body>
    {% include 'main/navbar.html' %}
    <br/>

    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
    integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
    crossorigin="anonymous"></script>
    -->
  </body>
</html>

main/templates/main/bookshelf.html
{% extends 'main/base.html' %}

{% block title %}{% endblock %}

{% block content %}

<h2><p>Книжкова полиця: {{ bookshelf }}</p></h2>
    {% if books %}

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Назва</th>
          <th scope="col">Автор</th>
          <th scope="col"></th>
        </tr>
      </thead>

      <tbody>
        {% for book in books %}
        <tr>
          <th scope="row"></th>
            <td><a href="{% url 'main:book' book.id %}" class="btn btn-light" role="button" >{{ book.title }}</a></td>
            <td>{{ book.author }}</td>
            <td><a href="{% url 'main:delete_book_from_bookshelf' book.id bookshelf.id %}"
                   class="btn btn-outline-danger" role="button" >Видалити</a></td>
        </tr>
        {% endfor %}

        {% else %}
            <p>Щоб додати книгу - спочатку знайдіть її через пошук. </p>

        {% endif %}

      </tbody>
    </table>

{% endblock %}

main/templates/main/bookshelves.html
{% extends 'main/base.html' %}

{% block title %}Книжкові полиці{% endblock %}

{% block content %}
<center>

<h2>Мої полиці:</h2>
    {% for bookshelf in bookshelves %}
    <div class="w-75 p-3">
        <div class="card">
            <h5 class="card-header">{{ bookshelf }}</h5>
            <div class="card-body">
                <a href="{% url 'main:bookshelf' bookshelf.id %}" class="btn btn-primary">Перейти до полиці</a>
                <a href="{% url 'main:delete_bookshelf' bookshelf.id %}" class="btn btn-danger">Видалити</a>
            </div>
        </div>
    </div>

    {% empty %}
        <p>Ви ще не створили жодної книжкової полиці</p>
    {% endfor %}

    <a href="{% url 'main:new_bookshelf' %}" class="btn btn-outline-warning" role="button" >Створити нову полицю</a>
    </center>

{% endblock %}

main/templates/main/feedback.html
{% extends 'main/base.html' %}

{% block title %}Головна сторінка{% endblock %}

{% block content %}
<form action="{% url 'main:feedback' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Надіслати відгук</button>
  </form>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}Головна сторінка{% endblock %}

{% block content %}

<center>
    {% for article in articles %}
    <div class="w-75 p-3">
        <div class="card text-center" >
            <div class="card-body">
                <h4 class="card-title">{{ article.title }}</h4>
                <a><p class="card-text"></p></a>
                <a href="{% url 'main:article' article.id %}" class="btn btn-primary">Перейти</a>
            </div>
            <div class="card-footer text-muted">
                {% for category in article.categories.all  %}
                {{ category }} /
                {% endfor %}
                {{ article.date_added }}
            </div>
        </div>
    </div>
<br/>
    {% endfor %}
    </center>

{% endblock %}

main/templates/main/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:home' %}">Literature Database</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <form method=POST action="{% url 'main:search_books' %}" class="d-flex" role="search">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Шукати книгу" aria-label="Search" name="searched">
        <button class="btn btn-outline-secondary" type="submit">Пошук</button>
      </form>

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:about' %}">Про проект</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:bookshelves' %}">Книжкові полиці</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Вихід</a>
        </li>
        {% else %}
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Зареєструватись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Увійти</a>
          </li>
        </ul>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

main/templates/main/new_bookshelf.html
{% extends 'main/base.html' %}

{% block title %}Нова полиця{% endblock %}

{% block content %}
  <p>Створити нову полицю: </p>

  <form action="{% url 'main:new_bookshelf' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">створити полицю</button>
  </form>

{% endblock %}

main/templates/main/old_base.html
{% load static %}

<!doctype html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">
</head>
<body>
    <aside>
        <span class="logo"><img src="{% static 'main/img/icons8-repository-100.png' %}" alt="logo">LDb</span>
        <h3>Навігація</h3>
        <ul>
            <a href="{% url 'main:home' %}"><li><i class="bi bi-house-door"></i></i> Головна</li></a>
            <a href="{% url 'main:about' %}"><li><i class="bi bi-book"></i> Про нас</li></a>
            <a href="{% url 'main:library' %}"><li>Бібліотека</li></a>
            <a href="{% url 'main:bookshelves' %}"><li>Книжкові полиці</li></a>
        </ul>
        <p>
            {% if user.is_authenticated %}
              Привіт, {{ user.username }}.
              <a href="{% url 'users:logout' %}">Вихід</a>
            {% else %}
            <ul>
              <a href="{% url 'users:register' %}"><li>Зареєструватись</li></a>
              <a href="{% url 'users:login' %}"><li>Увійти</li></a>
            </ul>
            {% endif %}
        </p>
        <style>a {text-decoration: none;}</style>

        <form method=POST action="{% url 'main:search_books' %}">
        {% csrf_token %}
        <input type="search" placeholder="Шукати книжки в бібліотеці" name="searched" aria-label="Search">
        <button type="submit">Пошук</button>
    </form>

    </aside>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

main/templates/main/rating.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Ваш заголовок</title>
  <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
  <ul class="btn btn-light list-inline rating-list">
    <li onclick="rate(10, {{ book.id }})">
      <i class="fa fa-star {% if book.user_rating > 9 %} checked {% endif %}" title="Rate10"></i></li>
      {{ book_r }}
    <li onclick="rate(9, {{ book.id }})">
      <i class="fa fa-star {% if book.user_rating > 8 %} checked {% endif %}" title="Rate 9"></i></li>
    <li onclick="rate(8, {{ book.id }})">
      <i class="fa fa-star {% if book.user_rating > 7 %} checked {% endif %}" title="Rate 8"></i></li>
    <li onclick="rate(7, {{ book.id }})">
      <i class="fa fa-star {% if book.user_rating > 6 %} checked {% endif %}" title="Rate 7"></i></li>
    <li onclick="rate(6, {{ book.id }})">
      <i class="fa fa-star {% if book.user_rating > 5 %} checked {% endif %}" title="Rate 6"></i></li>
    <li onclick="rate(5, {{ book.id }})">
      <i class="fa fa-star {% if book.user_rating > 4 %} checked {% endif %}" title="Rate 5"></i></li>
    <li onclick="rate(4, {{ book.id }})">
      <i class="fa fa-star {% if book.user_rating > 3 %} checked {% endif %}" title="Rate 4"></i></li>
    <li onclick="rate(3, {{ book.id }})">
      <i class="fa fa-star {% if book.user_rating > 2 %} checked {% endif %}" title="Rate 3"></i></li>
    <li onclick="rate(2, {{ book.id }})">
      <i class="fa fa-star {% if book.user_rating > 1 %} checked {% endif %}" title="Rate 2"></i></li>
    <li onclick="rate(1, {{ book.id }})">
      <i class="fa fa-star {% if book.user_rating > 0 %} checked {% endif %}" title="Rate 1"></i></li>
  </ul>
</body>
</html>